server:
  port: 8081
  servlet:
    context-path: /v1.0/
spring:
  application:
    name: app-vehicle-purchase-api
    version: develop
  sleuth:
     sampler:
        probability: 1
  datasource:
    url: jdbc:mysql:
    username: vehicles_username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 5
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 60000
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
azure:
  host:
    name: ${WEBSITE_SITE_NAME:localhost}
    slot: ${WEBSITE_SLOT_NAME:develop}
service:
---
server:
  port: ${PORT}
  servlet:
    context-path: /v1.0/
spring:
  config:
    activate:
      on-profile: release
  application:
    name: app-vehicle-purchase-api
    version: ${APP_VERSION}
  sleuth:
     sampler:
        probability: 1
  datasource:
    url: ${SQL_URL_CONECTION}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 5
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 60000
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
azure:
  host:
    name: ${WEBSITE_SITE_NAME:localhost}
    slot: ${WEBSITE_SLOT_NAME:develop}
service:
